export default {
    TEXT_PLAIN: "text/plain",
    TEXT_CSS: "text/css",
    TEXT_JAVASCRIPT: "text/javascript",
    IMAGE_GIF: "image/gif",
    IMAGE_PNG: "image/png",
    IMAGE_JPEG: "image/jpeg",
    IMAGE_BMP: "image/bmp",
    IMAGE_WEBP: "image/webp",
    AUDIO_MIDI: "audio/midi",
    AUDIO_MPEG: "audio/mpeg",
    AUDIO_WEBM: "audio/webm",
    AUDIO_OGG: "audio/ogg",
    AUDIO_WAV: "audio/wav",
    VIDEO_WEBM: "video/webm",
    VIDEO_OGG: "video/ogg",
    APPLICATION_OCTET_STREAM: "application/octet-stream",
    APPLICATION_PKCS12: "application/pkcs12",
    APPLICATION_VND_MSPOWERPOINT: "application/vnd.mspowerpoint",
    APPLICATION_XHTML_XML: "application/xhtml+xml",
    APPLICATION_XML: "application/xml",
    APPLICATION_PDF: "application/pdf"
};
