export type Minute = number;
export type Second = number;
export type Hour = number;

export enum ERROR_CODES {
    UNDERDEVELOPMENT = "UNDERDEVELOPMENT",
    ACCESS_DENY_USER = "ACCESS_DENY_USER",
    ACCESS_DENY_STORE = "ACCESS_DENY_STORE",
    ACCESS_DENY_PRODUCT = "ACCESS_DENY_PRODUCT",
    UNAUTHORIZED_USER = "UNAUTHORIZED_USER",
    UNEXIST_STORE = "UNEXIST_STORE",
    UNEXIST_PRODUCT = "UNEXIST_PRODUCT",
    UNEXIST_GROUP = "UNEXIST_GROUP",
    UNEXIST_USER = "UNEXIST_USER",
    UNDEFINED_JWK = "UNDEFINED_JWK"
}
